import * as c from './constants';
import { Command } from './types';

export const query = async (text: string) => {
  const [tab] = await chrome.tabs.query({ active: true, lastFocusedWindow: true });

  const commands: Command[] = [
    {
      id: 0,
      type: 'command',
      title: 'New tab',
      description: 'Open a new tab',
      message: { type: c.TABS_CREATE },
    },
    {
      id: 1,
      type: 'command',
      title: 'Bookmark',
      description: 'Bookmark the current page',
      message: { type: c.BOOKMARKS_CREATE },
    },
    {
      id: 2,
      type: 'command',
      title: tab.pinned ? 'Unpin tab' : 'Pin tab',
      description: tab.pinned ? 'Unpin the current tab' : 'Pin the current tab',
      message: { type: c.TABS_UPDATE_TOGGLE_PIN },
    },
    {
      id: 3,
      type: 'command',
      title: 'Fullscreen',
      description: 'Make the current window fullscreen',
      message: { type: c.BROWSER_FULLSCREEN },
    },
    {
      id: 4,
      type: 'command',
      title: tab.mutedInfo?.muted ? 'Unmute' : 'Mute',
      description: tab.mutedInfo?.muted ? 'Unmute the current tab' : 'Mute the current tab',
      message: { type: c.TABS_UPDATE_TOGGLE_MUTE },
    },
    {
      id: 5,
      type: 'command',
      title: 'Reload',
      description: 'Reload the current tab',
      message: { type: c.TABS_RELOAD },
    },
    {
      id: 6,
      type: 'command',
      title: 'Help',
      description: 'Get help with OmniX',
      message: { type: c.TABS_CREATE, payload: 'https://github.com/geekvijay/omnix' },
    },
    {
      id: 7,
      type: 'command',
      title: 'Compose Email',
      description: 'Compose a new email',
      message: { type: c.TABS_CREATE, payload: 'mailto:' },
    },
    {
      id: 8,
      type: 'command',
      title: 'Print',
      description: 'Print the current page',
      message: { type: c.BROWSER_PRINT },
    },
    {
      id: 9,
      type: 'command',
      title: 'New Notion Page',
      description: 'Create a new Notion page',
      message: { type: c.TABS_CREATE, payload: 'https://notion.new' },
    },
    {
      id: 10,
      type: 'command',
      title: 'New Google Sheet',
      description: 'Create a new Google Sheet',
      message: { type: c.TABS_CREATE, payload: 'https://sheets.new' },
    },
    {
      id: 11,
      type: 'command',
      title: 'New Google Doc',
      description: 'Create a new Google Doc',
      message: { type: c.TABS_CREATE, payload: 'https://docs.new' },
    },
    {
      id: 12,
      type: 'command',
      title: 'New Google Slides',
      description: 'Create a new Google Slides',
      message: { type: c.TABS_CREATE, payload: 'https://slides.new' },
    },
    {
      id: 13,
      type: 'command',
      title: 'New Google Form',
      description: 'Create a new Google Form',
      message: { type: c.TABS_CREATE, payload: 'https://forms.new' },
    },
    {
      id: 14,
      type: 'command',
      title: 'New Medium Story',
      description: 'Create a new Medium story',
      message: { type: c.TABS_CREATE, payload: 'https://story.new' },
    },
    {
      id: 15,
      type: 'command',
      title: 'New Github Repository',
      description: 'Create a new Github repository',
      message: { type: c.TABS_CREATE, payload: 'https://github.new' },
    },
    {
      id: 16,
      type: 'command',
      title: 'New Github Gist',
      description: 'Create a new Github gist',
      message: { type: c.TABS_CREATE, payload: 'https://gist.new' },
    },
    {
      id: 17,
      type: 'command',
      title: 'New Codepen',
      description: 'Create a new Codepen',
      message: { type: c.TABS_CREATE, payload: 'https://pen.new' },
    },
    {
      id: 18,
      type: 'command',
      title: 'New Excel Spreadsheet',
      description: 'Create a new Excel Spreadsheet',
      message: { type: c.TABS_CREATE, payload: 'https://excel.new' },
    },
    {
      id: 19,
      type: 'command',
      title: 'New PowerPoint Presentation',
      description: 'Create a new PowerPoint Presentation',
      message: { type: c.TABS_CREATE, payload: 'https://powerpoint.new' },
    },
    {
      id: 20,
      type: 'command',
      title: 'New Word Document',
      description: 'Create a new Word Document',
      message: { type: c.TABS_CREATE, payload: 'https://word.new' },
    },
    {
      id: 21,
      type: 'command',
      title: 'Create a whiteboard',
      description: 'Create a new whiteboard',
      message: { type: c.TABS_CREATE, payload: 'https://whiteboard.new' },
    },
    {
      id: 22,
      type: 'command',
      title: 'Create a recording',
      description: 'Create a new recording',
      message: { type: c.TABS_CREATE, payload: 'https://recording.new' },
    },
    {
      id: 23,
      type: 'command',
      title: 'New Figma Project',
      description: 'Create a new Figma project',
      message: { type: c.TABS_CREATE, payload: 'https://figma.new' },
    },
    {
      id: 24,
      type: 'command',
      title: 'New Figma Jam',
      description: 'Create a new Figma Jam',
      message: { type: c.TABS_CREATE, payload: 'https://figjam.new' },
    },
    {
      id: 25,
      type: 'command',
      title: 'New Product Hunt Post',
      description: 'Create a new Product Hunt post',
      message: { type: c.TABS_CREATE, payload: 'https://www.producthunt.com/posts/new' },
    },
    {
      id: 26,
      type: 'command',
      title: 'New X (Twitter) Post',
      description: 'Create a new X (Twitter) post',
      message: { type: c.TABS_CREATE, payload: 'https://x.com/intent/post' },
    },
    {
      id: 27,
      type: 'command',
      title: 'New Spotify Playlist',
      description: 'Create a new Spotify playlist',
      message: { type: c.TABS_CREATE, payload: 'https://playlist.new' },
    },
    {
      id: 28,
      type: 'command',
      title: 'New Canva design',
      description: 'Create a new Canva design',
      message: { type: c.TABS_CREATE, payload: 'https://canva.new' },
    },
    {
      id: 29,
      type: 'command',
      title: 'New Podcast Episode',
      description: 'Create a new Podcast Episode',
      message: { type: c.TABS_CREATE, payload: 'https://episode.new' },
    },
    {
      id: 30,
      type: 'command',
      title: 'Edit Photo',
      description: 'Edit the photo with Adobe Photoshop',
      message: { type: c.TABS_CREATE, payload: 'https://photo.new' },
    },
    {
      id: 31,
      type: 'command',
      title: 'Convert to PDF',
      description: 'Convert a file to PDF',
      message: { type: c.TABS_CREATE, payload: 'https://pdf.new' },
    },
    {
      id: 32,
      type: 'command',
      title: 'Scan a QR code',
      description: 'Scan a QR code with your camera',
      message: { type: c.TABS_CREATE, payload: 'https://scan.new' },
    },
    {
      id: 33,
      type: 'command',
      title: 'Add a task to Asana',
      description: 'Create a new task in Asana',
      message: { type: c.TABS_CREATE, payload: 'https://task.new' },
    },
    {
      id: 34,
      type: 'command',
      title: 'New Linear issue',
      description: 'Create a new Linear issue',
      message: { type: c.TABS_CREATE, payload: 'https://linear.new' },
    },
    {
      id: 35,
      type: 'command',
      title: 'Add a task to WIP',
      description: 'Create a new task in WIP',
      message: { type: c.TABS_CREATE, payload: 'https://todo.new' },
    },
    {
      id: 36,
      type: 'command',
      title: 'New Google Calendar event',
      description: 'Create a new event on Google Calendar',
      message: { type: c.TABS_CREATE, payload: 'https://cal.new' },
    },
    {
      id: 37,
      type: 'command',
      title: 'New Google Keep note',
      description: 'Create a new note in Google Keep',
      message: { type: c.TABS_CREATE, payload: 'https://note.new' },
    },
    {
      id: 38,
      type: 'command',
      title: 'New Google Meet',
      description: 'Create a new Google Meet meeting',
      message: { type: c.TABS_CREATE, payload: 'https://meet.new' },
    },
    {
      id: 39,
      type: 'command',
      title: 'Browsing history',
      description: 'Browse your browsing history',
      message: { type: c.TABS_CREATE, payload: 'chrome://history' },
    },
    {
      id: 40,
      type: 'command',
      title: 'Incognito mode',
      description: 'Open a new incognito window',
      message: { type: c.WINDOWS_CREATE_INCOGNITO },
    },
    {
      id: 41,
      type: 'command',
      title: 'Downloads',
      description: 'Browse your downloads',
      message: { type: c.TABS_CREATE, payload: 'chrome://downloads' },
    },
    {
      id: 42,
      type: 'command',
      title: 'Extensions',
      description: 'Manage your Chrome Extensions',
      message: { type: c.TABS_CREATE, payload: 'chrome://extensions' },
    },
    {
      id: 43,
      type: 'command',
      title: 'Settings',
      description: 'Manage your Chrome settings',
      message: { type: c.TABS_CREATE, payload: 'chrome://settings' },
    },
    {
      id: 44,
      type: 'command',
      title: 'Scroll to bottom',
      description: 'Scroll to the bottom of the page',
      message: { type: c.BROWSER_SCROLL_TO_BOTTOM },
    },
    {
      id: 45,
      type: 'command',
      title: 'Scroll to top',
      description: 'Scroll to the top of the page',
      message: { type: c.BROWSER_SCROLL_TO_TOP },
    },
    {
      id: 46,
      type: 'command',
      title: 'Go back',
      description: 'Go back in history for the current tab',
      message: { type: c.TABS_GO_BACK },
    },
    {
      id: 47,
      type: 'command',
      title: 'Go forward',
      description: 'Go forward in history for the current tab',
      message: { type: c.TABS_GO_FORWARD },
    },
    {
      id: 48,
      type: 'command',
      title: 'Duplicate tab',
      description: 'Duplicate the current tab',
      message: { type: c.TABS_DUPLICATE },
    },
    {
      id: 49,
      type: 'command',
      title: 'Close tab',
      description: 'Close the current tab',
      message: { type: c.TABS_REMOVE },
    },
    {
      id: 50,
      type: 'command',
      title: 'Close window',
      description: 'Close the current window',
      message: { type: c.WINDOWS_REMOVE },
    },
    {
      id: 51,
      type: 'command',
      title: 'Manage browsing data',
      description: 'Manage your browsing data',
      message: { type: c.TABS_CREATE, payload: 'chrome://settings/clearBrowserData' },
    },
    {
      id: 52,
      type: 'command',
      title: 'Clear all browsing data',
      description: 'Clear all of your browsing data',
      message: { type: c.BROWSING_DATA_REMOVE_ALL },
    },
    {
      id: 53,
      type: 'command',
      title: 'Clear browsing history',
      description: 'Clear all of your browsing history',
      message: { type: c.BROWSING_DATA_REMOVE_HISTORY },
    },
    {
      id: 54,
      type: 'command',
      title: 'Clear cookies',
      description: 'Clear all of your cookies',
      message: { type: c.BROWSING_DATA_REMOVE_COOKIES },
    },
    {
      id: 55,
      type: 'command',
      title: 'Clear cache',
      description: 'Clear all of your cache',
      message: { type: c.BROWSING_DATA_REMOVE_CACHE },
    },
    {
      id: 56,
      type: 'command',
      title: 'Clear local storage',
      description: 'Clear all of your local storage',
      message: { type: c.BROWSING_DATA_REMOVE_LOCAL_STORAGE },
    },
    {
      id: 57,
      type: 'command',
      title: 'Clear passwords',
      description: 'Clear all of your passwords',
      message: { type: c.BROWSING_DATA_REMOVE_PASSWORDS },
    },
  ];

  return text ? commands.filter((command) => command.title.toLowerCase().includes(text.toLowerCase())) : commands;
};
